### ISSUE TITLE
Provide button to invert filter rules.

### ISSUE THREAD

**Issue by majestrate** [jacquerie/stop-the-bullshit#7]
This extension would be more useful to more people If there was an option to invert the filter rules to only show "fake" news.

**Comment by fluorine** [comment]
I agree. Leftist propaganda can be very funny.

They lost all credibility when Trump won, after all bullshit of false polls and non-news that they pushed.

Mainstream media is even more dangerous than fake news because they are full of half truths, which are more dangerous and credible for the public, but not any more.

It would be nice to fork this project to reject mainstream propaganda and publish it in r/The_Donald and /pol/. I bet someone already did fork this for the benefit of conservatives.

**Comment by jacquerie** [comment]
As tptacek on HN correctly inferred, `stop-the-bullshit` aims to block these kind of websites:

> No, fake news = spam sites built from scripts consisting largely of a backcatalog nonsense stories ("Pope endorses Putin for US Presidential Election") with a one or two carefully produced fake stories as a "payload", instead of a purchasing call-to-action like other webspam sites.
(https://news.ycombinator.com/item?id=12999887)

I don't and won't care about websites that stretch the truth to accommodate an agenda. I just want to punish spammers.

> It would be nice to fork this project to reject mainstream propaganda and publish it in r/The_Donald and /pol/. I bet someone already did fork this for the benefit of conservatives.

Of course they can, but they must share back their improvements, as per the GPL.

To answer @majestrate, no, I'm not going to implement that. It's like asking for a reverse spam filter that puts all your work email in the spam folder, and all your spam in your inbox.
